build:
  nodes:
    analysis:
      environment:
        php:
          version: "8.2"
      dependencies:
        before:
          - composer install --no-interaction
      tests:
        override:
          - command: |
              XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover build/logs/clover.xml
            coverage:
              file: build/logs/clover.xml
              format: clover
